# Generated by Django 2.1.1 on 2018-09-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('size', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('alignment', models.CharField(max_length=20)),
                ('ac', models.IntegerField()),
                ('hp', models.CharField(max_length=12)),
                ('speed', models.TextField()),
                ('str_mod', models.IntegerField()),
                ('dex_mod', models.IntegerField()),
                ('con_mod', models.IntegerField()),
                ('int_mod', models.IntegerField()),
                ('wis_mod', models.IntegerField()),
                ('cha_mod', models.IntegerField()),
                ('saving_throws', models.TextField(null=True)),
                ('skills', models.TextField(null=True)),
                ('vulnerabilies', models.TextField(null=True)),
                ('resistances', models.TextField(null=True)),
                ('immunities', models.TextField(null=True)),
                ('senses', models.TextField(null=True)),
                ('languages', models.TextField(null=True)),
                ('cr', models.FloatField()),
                ('xp', models.IntegerField()),
                ('traits', models.TextField()),
                ('actions', models.TextField()),
                ('legendary_actions', models.TextField(null=True)),
            ],
        ),
    ]
