# Generated by Django 2.1.1 on 2018-09-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='ac',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='actions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='alignment',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='cha_mod',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='con_mod',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='cr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='dex_mod',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='hp',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='int_mod',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='size',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='speed',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='str_mod',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='traits',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='wis_mod',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='xp',
            field=models.IntegerField(null=True),
        ),
    ]
