# Generated by Django 2.1.1 on 2018-09-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Using an existing name will overwrite that entry. <br> Using a new name will create a new entry <br>', max_length=50, unique=True)),
                ('level', models.IntegerField()),
                ('ac', models.IntegerField()),
                ('initiative', models.IntegerField()),
            ],
        ),
    ]
